### ISSUE TITLE
synchronize: does not work over docker connection.

### ISSUE THREAD

**Issue by bbaassssiiee** [ansible/ansible-container-demo#2]
ansible-container_1  | TASK [django-gunicorn : Copy source] *******************************************
ansible-container_1  | fatal: [django]: FAILED! => {"changed": false, "failed": true, "msg": "synchronize uses rsync to function. rsync needs to connect to the remote host via ssh or a direct filesystem copy. This remote host is being accessed via docker instead so it cannot work."}

**Comment by chouseknecht** [comment]
@bbaassssiiee - you need to use Ansible Container v0.3.0. To do so requires [running from source](http://docs.ansible.com/ansible-container/installation.html#running-from-source), rather than installing from pip.

**Comment by chouseknecht** [comment]
@bbaassssiiee, closing this issue, because the [Travis test](https://travis-ci.org/ansible/ansible-container-demo) demonstrates that the build does work, and indeed with the latest Ansible Container installed from source, synchronize works over the Docker connection plugin. 

Thank you for trying out the demo, and for your interest in Ansible Container. I really appreciate you taking the time to open issues and provide feedback. 

Thanks!

--Chris
